CREATE DATABASE EPATEC;
go
USE EPATEC;

CREATE TABLE CATEGORY(
	CA_ID varchar(255),
	CA_Description varchar(255) NULL,
	CA_Status varchar(255),
	PRIMARY KEY(CA_ID)
)

CREATE TABLE CLIENT(
	C_ID int NOT NULL,
	C_Name varchar(255) NOT NULL,
	C_LName varchar(255) NOT NULL,
	C_Address varchar(255) NOT NULL,
	C_Phone int NOT NULL,
	C_Date date,
	C_Penalization int DEFAULT 0 NOT NULL,
	C_Status varchar(255),
	PRIMARY KEY(C_ID)
	)

CREATE TABLE WORKER(
	W_ID int NOT NULL,
	W_Name varchar(255) NULL,
	W_LName varchar(255) NULL,
	W_Address varchar(255) NULL,
	W_Password varchar(255) DEFAULT '1234' NULL,
	PRIMARY KEY(W_ID)
)

CREATE TABLE EORDER(
	O_ID int NOT NULL,
	O_Priority int DEFAULT 0 NULL,
	O_Status char(255) DEFAULT 'not delivered' NOT NULL,
	O_Date date  DEFAULT getdate() NULL,
	O_PPhone int,
	S_ID INT,
	C_ID INT,
	W_ID INT,
	PRIMARY KEY(O_ID)
)


CREATE TABLE EPROVIDER(
	P_ID int NOT NULL,
	P_Name char(255) NOT NULL,
	P_LName char(255) NOT NULL,
	P_Address char(255) NOT NULL,
	P_Date date,
	P_Status varchar(255),
	PRIMARY KEY(P_ID)
)

CREATE TABLE PRODUCT(
	PR_ID int NOT NULL,
	PR_Name varchar(255) NOT NULL,
	PR_Price int,
	PR_Exempt int,
	PR_Description varchar(255),
	PR_Quantity int,
	PR_Status varchar(255),
	S_ID INT,
	P_ID INT,
	PRIMARY KEY(PR_ID)
)


CREATE TABLE SUCURSAL(
	S_ID int NOT NULL,
	S_Name char(255) NOT NULL,
	S_Address char(255) NOT NULL,
	PRIMARY KEY(S_ID)

)
CREATE TABLE ORDERXPRODUCT(
	OXP_ID int not null,
	PR_Name varchar(255),
	PR_Amount int,
	PR_Price int,
	O_ID INT,
	PR_ID INT,
	PRIMARY KEY(OXP_ID)
)

CREATE TABLE EROLE(
	R_ID int,
	R_Description varchar(255),
	PRIMARY KEY(R_ID)
)
CREATE TABLE CATEXPRODUCT(
	CXP_ID int,
	CXP_Status varchar(255),
	CA_ID varchar(255),
	PR_ID INT,
	PRIMARY KEY(CXP_ID)
)
CREATE TABLE WXR(
	WXR_ID int,
	W_ID INT,
	R_ID INT,
	PRIMARY KEY(WXR_ID)
)


ALTER TABLE ORDERXPRODUCT ADD FOREIGN KEY(O_ID)
REFERENCES EORDER(O_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE ORDERXPRODUCT ADD FOREIGN KEY(PR_ID)
REFERENCES PRODUCT(PR_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE EORDER ADD FOREIGN KEY(S_ID)
REFERENCES SUCURSAL(S_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE EORDER ADD FOREIGN KEY(C_ID)
REFERENCES CLIENT(C_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE EORDER ADD FOREIGN KEY(W_ID)
REFERENCES WORKER(W_ID)
ON DELETE CASCADE
ON UPDATE CASCADE


ALTER TABLE WXR ADD FOREIGN KEY(W_ID)
REFERENCES WORKER(W_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE WXR ADD FOREIGN KEY(R_ID)
REFERENCES EROLE(R_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE CATEXPRODUCT ADD FOREIGN KEY(CA_ID)
REFERENCES CATEGORY(CA_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE CATEXPRODUCT ADD FOREIGN KEY(PR_ID)
REFERENCES PRODUCT(PR_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE PRODUCT ADD FOREIGN KEY(P_ID)
REFERENCES EPROVIDER(P_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE PRODUCT ADD FOREIGN KEY(S_ID)
REFERENCES SUCURSAL(S_ID)

INSERT INTO ROLE VALUES(1,'Dependiente')
INSERT INTO WORKER VALUES(1,'Bryan','Masis','Cartago','coso','Available')
